### ISSUE TITLE
Map render objects only in it's viewport

### ISSUE THREAD

**Issue by eko24** [MaximPetrichuk/xyMap#1]
Tested in Chrome v54.0.2840.99 m
See this gif:
![8scnegc - imgur](https://cloud.githubusercontent.com/assets/758017/21015882/44c7dfde-bd6c-11e6-9b4a-39208f03db98.gif)

Fiddle to repoduce: https://jsfiddle.net/Petrichuk/qcg1k6ev/

_Hello from HabraHabr :)_

**Comment by MaximPetrichuk** [comment]
Thanks, 
I fixed this bug.
